author: "Tobe O <thosakwe@gmail.com>"
description: "Material menu for Angular2."
homepage: "https://github.com/thosakwe/material_menu"
name: "material_menu"
version: "1.0.0"
dependencies: 
  angular2: "^2.2.0"
  angular2_components: "^0.2.1"
dev_dependencies: 
  browser: "^0.10.0+2"
  material_toolbar: "^1.0.0"
environment: 
  sdk: ">=1.19.0"
transformers: 
  - 
    angular2: 
      entry_points: "web/main.dart"
      platform_directives: 
        - "package:angular2/common.dart#COMMON_DIRECTIVES"
      platform_pipes: 
        - "package:angular2/common.dart#COMMON_PIPES"
