author: Tobe O <thosakwe@gmail.com>
description: Material menu for Angular2.
homepage: https://github.com/thosakwe/material_menu
name: material_menu
version: 2.0.0
dependencies: 
  angular2: ">=3.0.0-beta <4.0.0"
  angular_components: ">=0.5.0-beta <2.0.0"
dev_dependencies: 
  browser: 0.10.0
  material_toolbar: ^2.0.0
environment: 
  sdk: ">=1.23.0-beta"
transformers: 
  - angular2: 
      entry_points: web/main.dart
      platform_directives: 
        - package:angular2/common.dart#COMMON_DIRECTIVES
      platform_pipes: 
        - package:angular2/common.dart#COMMON_PIPES
